### ISSUE TITLE
Calculate integrate power from dose meter data

### ISSUE THREAD

**Issue by gmclapp** [Austin-Czyzewski/Actinium-Growth-Curves#7]
Does it make sense to do this in our script? Right now I think dose data gets added to a sheet and then a different column is pasted into the beam data csv for this script. I think we could probably remove a step if we added this feature.

**Comment by Austin-Czyzewski** [comment]
Yeah, I think the littler excel mutations we have to do is the best

**Comment by gmclapp** [comment]
Austin closed this ages ago.
